name: CI for Acceptance Branch

on:
  push:
    branches:
      - acceptance

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and run tests with Maven
        run: xvfb-run -a mvn clean package

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: jar-executable
          path: target/*.jar
