name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: xvfb-run -a mvn clean package

      - name: Release the app
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
